### Create signup using invalid details

POST http://localhost:5000/api/signups
User-Agent: rest-client
Content-Type: application/json

{
    "Email": "sally@example.com",
    "Password": "password",
    "ConfirmedPassword": "password1"
}

### Create signup using valid details

POST http://localhost:5000/api/signups
User-Agent: rest-client
Content-Type: application/json

{
    "Email": "bob@example.com",
    "Password": "password",
    "ConfirmedPassword": "password"
}