### Get token using invalid credentials

POST http://localhost:5000/api/tokens
User-Agent: rest-client
Content-Type: application/json

{
    "Email": "sally@example.com",
    "Password": "password",
}

### Get Token using valid credentials

POST http://localhost:5000/api/tokens
User-Agent: rest-client
Content-Type: application/json

{
    "Email": "bob@example.com",
    "Password": "password"
}